# fly.toml app configuration file generated for knowledgex-engine on 2025-01-30T10:15:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'knowledgex-engine'
primary_region = 'sjc'

[build]
  dockerfile = "apps/engine/Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
