services:
  engine:
    build:
      context: ./apps/engine
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/engine:/app
    ports:
      - "8000:8000" # adjust port as needed
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: on-failure:1
    networks:
      - supabase_network_knowledgex
  studio:
    build:
      context: ./
      dockerfile: apps/studio/Dockerfile.dev
    volumes:
      - ./apps/studio:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./apps/studio/.env.local # ✅ This ensures .env.local is loaded
    environment:
      - NODE_ENV=development
      # Enable Next.js specific features
      - WATCHPACK_POLLING=true
      - SUPABASE_URL=http://host.docker.internal:44321
    restart: on-failure:1
    networks:
      - supabase_network_knowledgex

networks:
  supabase_network_knowledgex:
    external: true
