services:
  engine:
    build:
      context: ./
      dockerfile: apps/engine/Dockerfile.dev
    volumes:
      - ./apps/engine/src:/app/apps/engine/src
      - ./apps/interfaces:/app/apps/interfaces
    ports:
      - "8000:8000" # adjust port as needed
    environment:
      - "POSTGRES_URL=postgresql://postgres:postgres@localhost:44322/postgres"
    extra_hosts:
      - "localhost:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: on-failure:1
  studio:
    build:
      context: ./
      dockerfile: apps/studio/Dockerfile.dev
    volumes:
      - ./apps/studio/src:/app/apps/studio/src
      - ./apps/studio/public:/app/apps/studio/public
      - ./apps/shared/src:/app/apps/shared/src
      - ./apps/interfaces:/app/apps/interfaces
    ports:
      - "3000:3000"
    env_file:
      - ./apps/studio/.env.local # ✅ This ensures .env.local is loaded
    environment:
      - NODE_ENV=development
      # Enable Next.js specific features
      - WATCHPACK_POLLING=true
    extra_hosts:
      - "localhost:host-gateway"
    restart: on-failure:1
