services:
  engine:
    build:
      context: ./apps/engine
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/engine:/app
      - /app/.venv
    ports:
      - "8000:8000" # adjust port as needed
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: on-failure:1
  studio:
    build:
      context: ./
      dockerfile: apps/studio/Dockerfile.dev
    volumes:
      - ./apps/studio:/app
      # Exclude node_modules from volume mounting
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # Enable Next.js specific features
      - WATCHPACK_POLLING=true
    restart: on-failure:1
