import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";

const sansFont = DM_Sans({
	variable: "--font-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "KnowledgeX",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${sansFont.variable}`}>
			<body className="antialiased">
				<Toaster position="top-right" />
				<div className="flex h-screen">
					<Navbar />
					<main className="flex-1">{children}</main>
				</div>
			</body>
		</html>
	);
}
