FROM node:20-slim AS builder
RUN corepack enable && corepack prepare pnpm@latest --activate

# Use Node 20 slim as base
FROM builder AS workspace

WORKDIR /app
COPY . .

# Copy the package.json and pnpm-lock.yaml before installing dependencies
RUN pnpm --filter studio deploy pruned

FROM builder

WORKDIR /app

COPY --from=workspace /app/pruned .

# Ensure .env.local is recognized
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Expose port 3000 (Next.js default)
EXPOSE 3000

# Start the development server with hot reloading
CMD ["pnpm", "dev"]
