FROM node:20-slim AS base
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app
ENV WATCHPACK_POLLING=true
ENV NODE_ENV=development

# Dependencies stage
FROM base AS deps
# Copy only files needed for installation
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/studio/package.json ./apps/studio/
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
# Debug and print the list of installed packages
RUN pnpm deploy --filter=studio bundle

# Development stage
FROM base

COPY ./apps/studio .
COPY --from=deps /app/bundle .

# Mount source code at runtime instead of copying
EXPOSE 3000
CMD ["pnpm", "dev"]
